// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM76H4EKiKCVnWwHO1N80DF7GQMHmepow',
    appId: '1:412729662792:web:5a35fefac84454d0b2a77d',
    messagingSenderId: '412729662792',
    projectId: 'jasmani-sehat',
    authDomain: 'jasmani-sehat.firebaseapp.com',
    storageBucket: 'jasmani-sehat.firebasestorage.app',
    measurementId: 'G-QJBNTEH342',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdHwU70P-e07bMhLaVtRg8RzRF5SuLvA',
    appId: '1:412729662792:android:a2c31f5de1ff8b2bb2a77d',
    messagingSenderId: '412729662792',
    projectId: 'jasmani-sehat',
    storageBucket: 'jasmani-sehat.firebasestorage.app',
  );
}
